type Student @table {
  studentId: String!
  firstName: String!
  lastName: String!
  email: String!
  department: String!
  program: String!
  yearOfStudy: Int!
  createdAt: Timestamp!
  bio: String
  profilePictureUrl: String
  contactNumber: String
}

type Group @table {
  name: String!
  description: String!
  groupType: String!
  createdAt: Timestamp!
  adminStudentId: Student!
  coverImageUrl: String
}

type Membership @table(key: ["student", "group"]) {
  student: Student!
  group: Group!
  joinedAt: Timestamp!
}

type Post @table {
  student: Student!
  content: String!
  createdAt: Timestamp!
  group: Group
  imageUrl: String
  documentUrl: String
}

type DirectMessage @table {
  sender: Student!
  receiver: Student!
  messageContent: String!
  sentAt: Timestamp!
}

type Comment @table {
  student: Student!
  post: Post!
  commentContent: String!
  createdAt: Timestamp!
}